// <auto-generated />
using System;
using CRUD_Operation_JqueryAJAX.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRUD_Operation_JqueryAJAX.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20230905154006_Hotel_table")]
    partial class Hotel_table
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CRUD_Operation_JqueryAJAX.Models.HotelModel", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"), 1L, 1);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DishImageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(800)");

                    b.Property<string>("DishName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Is_deleted")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("DateTime");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.ToTable("tbl_HotelData");
                });
#pragma warning restore 612, 618
        }
    }
}
